services:
  db:
    image: postgres:15.3-alpine
    container_name: stakeoutbet-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stakeoutbet_db}
      POSTGRES_USER: ${POSTGRES_USER:-stakeout_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
    ports:
      - "5434:5432"
    # volumes:
    #   - ./dbdata:/var/lib/postgresql/data
    #   - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stakeoutnet

  adminer:
    image: adminer
    container_name: stakeoutbet_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - stakeoutnet
      
  ngrok:
    image: ngrok/ngrok:latest
    container_name: stakeoutbet-ngrok
    restart: always
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:-}
    command: http host.docker.internal:4000
    networks:
      - stakeoutnet

networks:
  stakeoutnet:
    driver: bridge